// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v3.19.6
// source: update_metadata.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire'

export const protobufPackage = 'chromeos_update_engine'

export interface Extent {
  startBlock?: number | undefined
  numBlocks?: number | undefined
}

export interface Signatures {
  signatures: Signatures_Signature[]
}

export interface Signatures_Signature {
  /** @deprecated */
  version?: number | undefined
  data?: Uint8Array | undefined
  /**
   * The DER encoded signature size of EC keys is nondeterministic for
   * different input of sha256 hash. However, we need the size of the
   * serialized signatures protobuf string to be fixed before signing;
   * because this size is part of the content to be signed. Therefore, we
   * always pad the signature data to the maximum possible signature size of
   * a given key. And the payload verifier will truncate the signature to
   * its correct size based on the value of |unpadded_signature_size|.
   */
  unpaddedSignatureSize?: number | undefined
}

export interface PartitionInfo {
  size?: number | undefined
  hash?: Uint8Array | undefined
}

export interface InstallOperation {
  type: InstallOperation_Type
  /**
   * Only minor version 6 or newer support 64 bits |data_offset| and
   * |data_length|, older client will read them as uint32.
   * The offset into the delta file (after the protobuf)
   * where the data (if any) is stored
   */
  dataOffset?: number | undefined
  /** The length of the data in the delta file */
  dataLength?: number | undefined
  /** Ordered list of extents that are read from (if any) and written to. */
  srcExtents: Extent[]
  /**
   * Byte length of src, equal to the number of blocks in src_extents *
   * block_size. It is used for BSDIFF and SOURCE_BSDIFF, because we need to
   * pass that external program the number of bytes to read from the blocks we
   * pass it.  This is not used in any other operation.
   */
  srcLength?: number | undefined
  dstExtents: Extent[]
  /**
   * Byte length of dst, equal to the number of blocks in dst_extents *
   * block_size. Used for BSDIFF and SOURCE_BSDIFF, but not in any other
   * operation.
   */
  dstLength?: number | undefined
  /**
   * Optional SHA 256 hash of the blob associated with this operation.
   * This is used as a primary validation for http-based downloads and
   * as a defense-in-depth validation for https-based downloads. If
   * the operation doesn't refer to any blob, this field will have
   * zero bytes.
   */
  dataSha256Hash?: Uint8Array | undefined
  /**
   * Indicates the SHA 256 hash of the source data referenced in src_extents at
   * the time of applying the operation. If present, the update_engine daemon
   * MUST read and verify the source data before applying the operation.
   */
  srcSha256Hash?: Uint8Array | undefined
}

// @ts-expect-error TS1294
export enum InstallOperation_Type {
  /** REPLACE - Replace destination extents w/ attached data. */
  REPLACE = 0,
  /** REPLACE_BZ - Replace destination extents w/ attached bzipped data. */
  REPLACE_BZ = 1,
  /**
   * MOVE - Move source extents to target extents.
   *
   * @deprecated
   */
  MOVE = 2,
  /**
   * BSDIFF - The data is a bsdiff binary diff.
   *
   * @deprecated
   */
  BSDIFF = 3,
  /** SOURCE_COPY - On minor version 2 or newer, these operations are supported: */
  SOURCE_COPY = 4,
  /** SOURCE_BSDIFF - Like BSDIFF, but read from source partition */
  SOURCE_BSDIFF = 5,
  /**
   * REPLACE_XZ - On minor version 3 or newer and on major version 2 or newer, these
   * operations are supported:
   */
  REPLACE_XZ = 8,
  /** ZERO - On minor version 4 or newer, these operations are supported: */
  ZERO = 6,
  /** DISCARD - Discard the destination blocks, reading as undefined. */
  DISCARD = 7,
  /** BROTLI_BSDIFF - Like SOURCE_BSDIFF, but compressed with brotli. */
  BROTLI_BSDIFF = 10,
  /** PUFFDIFF - On minor version 5 or newer, these operations are supported: */
  PUFFDIFF = 9,
  /** ZUCCHINI - On minor version 8 or newer, these operations are supported: */
  ZUCCHINI = 11,
  /** LZ4DIFF_BSDIFF - On minor version 9 or newer, these operations are supported: */
  LZ4DIFF_BSDIFF = 12,
  LZ4DIFF_PUFFDIFF = 13,
  /** REPLACE_ZSTD - On minor version 10 or newer, these operations are supported: */
  REPLACE_ZSTD = 14,
  UNRECOGNIZED = -1
}

export function installOperation_TypeFromJSON(object: any): InstallOperation_Type {
  switch (object) {
    case 0:
    case 'REPLACE':
      return InstallOperation_Type.REPLACE
    case 1:
    case 'REPLACE_BZ':
      return InstallOperation_Type.REPLACE_BZ
    case 2:
    case 'MOVE':
      return InstallOperation_Type.MOVE
    case 3:
    case 'BSDIFF':
      return InstallOperation_Type.BSDIFF
    case 4:
    case 'SOURCE_COPY':
      return InstallOperation_Type.SOURCE_COPY
    case 5:
    case 'SOURCE_BSDIFF':
      return InstallOperation_Type.SOURCE_BSDIFF
    case 8:
    case 'REPLACE_XZ':
      return InstallOperation_Type.REPLACE_XZ
    case 6:
    case 'ZERO':
      return InstallOperation_Type.ZERO
    case 7:
    case 'DISCARD':
      return InstallOperation_Type.DISCARD
    case 10:
    case 'BROTLI_BSDIFF':
      return InstallOperation_Type.BROTLI_BSDIFF
    case 9:
    case 'PUFFDIFF':
      return InstallOperation_Type.PUFFDIFF
    case 11:
    case 'ZUCCHINI':
      return InstallOperation_Type.ZUCCHINI
    case 12:
    case 'LZ4DIFF_BSDIFF':
      return InstallOperation_Type.LZ4DIFF_BSDIFF
    case 13:
    case 'LZ4DIFF_PUFFDIFF':
      return InstallOperation_Type.LZ4DIFF_PUFFDIFF
    case 14:
    case 'REPLACE_ZSTD':
      return InstallOperation_Type.REPLACE_ZSTD
    case -1:
    case 'UNRECOGNIZED':
    default:
      return InstallOperation_Type.UNRECOGNIZED
  }
}

export function installOperation_TypeToJSON(object: InstallOperation_Type): string {
  switch (object) {
    case InstallOperation_Type.REPLACE:
      return 'REPLACE'
    case InstallOperation_Type.REPLACE_BZ:
      return 'REPLACE_BZ'
    case InstallOperation_Type.MOVE:
      return 'MOVE'
    case InstallOperation_Type.BSDIFF:
      return 'BSDIFF'
    case InstallOperation_Type.SOURCE_COPY:
      return 'SOURCE_COPY'
    case InstallOperation_Type.SOURCE_BSDIFF:
      return 'SOURCE_BSDIFF'
    case InstallOperation_Type.REPLACE_XZ:
      return 'REPLACE_XZ'
    case InstallOperation_Type.ZERO:
      return 'ZERO'
    case InstallOperation_Type.DISCARD:
      return 'DISCARD'
    case InstallOperation_Type.BROTLI_BSDIFF:
      return 'BROTLI_BSDIFF'
    case InstallOperation_Type.PUFFDIFF:
      return 'PUFFDIFF'
    case InstallOperation_Type.ZUCCHINI:
      return 'ZUCCHINI'
    case InstallOperation_Type.LZ4DIFF_BSDIFF:
      return 'LZ4DIFF_BSDIFF'
    case InstallOperation_Type.LZ4DIFF_PUFFDIFF:
      return 'LZ4DIFF_PUFFDIFF'
    case InstallOperation_Type.REPLACE_ZSTD:
      return 'REPLACE_ZSTD'
    case InstallOperation_Type.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED'
  }
}

/**
 * Hints to VAB snapshot to skip writing some blocks if these blocks are
 * identical to the ones on the source image. The src & dst extents for each
 * CowMergeOperation should be contiguous, and they're a subset of an OTA
 * InstallOperation.
 * During merge time, we need to follow the pre-computed sequence to avoid
 * read after write, similar to the inplace update schema.
 */
export interface CowMergeOperation {
  type?: CowMergeOperation_Type | undefined
  srcExtent?: Extent | undefined
  dstExtent?: Extent | undefined
  /**
   * For COW_XOR, source location might be unaligned, so this field is in range
   * [0, block_size), representing how much should the src_extent shift toward
   * larger block number. If this field is non-zero, then src_extent will
   * include 1 extra block in the end, as the merge op actually references the
   * first |src_offset| bytes of that extra block. For example, if |dst_extent|
   * is [10, 15], |src_offset| is 500, then src_extent might look like [25, 31].
   * Note that |src_extent| contains 1 extra block than the |dst_extent|.
   */
  srcOffset?: number | undefined
}

// @ts-expect-error TS1294
export enum CowMergeOperation_Type {
  /** COW_COPY - identical blocks */
  COW_COPY = 0,
  /** COW_XOR - used when src/dst blocks are highly similar */
  COW_XOR = 1,
  /** COW_REPLACE - Raw replace operation */
  COW_REPLACE = 2,
  UNRECOGNIZED = -1
}

export function cowMergeOperation_TypeFromJSON(object: any): CowMergeOperation_Type {
  switch (object) {
    case 0:
    case 'COW_COPY':
      return CowMergeOperation_Type.COW_COPY
    case 1:
    case 'COW_XOR':
      return CowMergeOperation_Type.COW_XOR
    case 2:
    case 'COW_REPLACE':
      return CowMergeOperation_Type.COW_REPLACE
    case -1:
    case 'UNRECOGNIZED':
    default:
      return CowMergeOperation_Type.UNRECOGNIZED
  }
}

export function cowMergeOperation_TypeToJSON(object: CowMergeOperation_Type): string {
  switch (object) {
    case CowMergeOperation_Type.COW_COPY:
      return 'COW_COPY'
    case CowMergeOperation_Type.COW_XOR:
      return 'COW_XOR'
    case CowMergeOperation_Type.COW_REPLACE:
      return 'COW_REPLACE'
    case CowMergeOperation_Type.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED'
  }
}

/** Describes the update to apply to a single partition. */
export interface PartitionUpdate {
  /**
   * A platform-specific name to identify the partition set being updated. For
   * example, in Chrome OS this could be "ROOT" or "KERNEL".
   */
  partitionName: string
  /**
   * Whether this partition carries a filesystem with post-install program that
   * must be run to finalize the update process. See also |postinstall_path| and
   * |filesystem_type|.
   */
  runPostinstall?: boolean | undefined
  /**
   * The path of the executable program to run during the post-install step,
   * relative to the root of this filesystem. If not set, the default "postinst"
   * will be used. This setting is only used when |run_postinstall| is set and
   * true.
   */
  postinstallPath?: string | undefined
  /**
   * The filesystem type as passed to the mount(2) syscall when mounting the new
   * filesystem to run the post-install program. If not set, a fixed list of
   * filesystems will be attempted. This setting is only used if
   * |run_postinstall| is set and true.
   */
  filesystemType?: string | undefined
  /**
   * If present, a list of signatures of the new_partition_info.hash signed with
   * different keys. If the update_engine daemon requires vendor-signed images
   * and has its public key installed, one of the signatures should be valid
   * for /postinstall to run.
   */
  newPartitionSignature: Signatures_Signature[]
  oldPartitionInfo?: PartitionInfo | undefined
  newPartitionInfo?: PartitionInfo | undefined
  /**
   * The list of operations to be performed to apply this PartitionUpdate. The
   * associated operation blobs (in operations[i].data_offset, data_length)
   * should be stored contiguously and in the same order.
   */
  operations: InstallOperation[]
  /**
   * Whether a failure in the postinstall step for this partition should be
   * ignored.
   */
  postinstallOptional?: boolean | undefined
  /** The extent for data covered by verity hash tree. */
  hashTreeDataExtent?: Extent | undefined
  /** The extent to store verity hash tree. */
  hashTreeExtent?: Extent | undefined
  /** The hash algorithm used in verity hash tree. */
  hashTreeAlgorithm?: string | undefined
  /** The salt used for verity hash tree. */
  hashTreeSalt?: Uint8Array | undefined
  /** The extent for data covered by FEC. */
  fecDataExtent?: Extent | undefined
  /** The extent to store FEC. */
  fecExtent?: Extent | undefined
  /** The number of FEC roots. */
  fecRoots?: number | undefined
  /**
   * Per-partition version used for downgrade detection, added
   * as an effort to support partial updates. For most partitions,
   * this is the build timestamp.
   */
  version?: string | undefined
  /**
   * A sorted list of CowMergeOperation. When writing cow, we can choose to
   * skip writing the raw bytes for these extents. During snapshot merge, the
   * bytes will read from the source partitions instead.
   */
  mergeOperations: CowMergeOperation[]
  /**
   * Estimated size for COW image. This is used by libsnapshot
   * as a hint. If set to 0, libsnapshot should use alternative
   * methods for estimating size.
   */
  estimateCowSize?: number | undefined
  /**
   * Information about the cow used by Cow Writer to specify
   * number of cow operations to be written
   */
  estimateOpCountMax?: number | undefined
}

export interface DynamicPartitionGroup {
  /** Name of the group. */
  name: string
  /**
   * Maximum size of the group. The sum of sizes of all partitions in the group
   * must not exceed the maximum size of the group.
   */
  size?: number | undefined
  /** A list of partitions that belong to the group. */
  partitionNames: string[]
}

export interface VABCFeatureSet {
  threaded?: boolean | undefined
  batchWrites?: boolean | undefined
}

/** Metadata related to all dynamic partitions. */
export interface DynamicPartitionMetadata {
  /**
   * All updatable groups present in |partitions| of this DeltaArchiveManifest.
   * - If an updatable group is on the device but not in the manifest, it is
   *   not updated. Hence, the group will not be resized, and partitions cannot
   *   be added to or removed from the group.
   * - If an updatable group is in the manifest but not on the device, the group
   *   is added to the device.
   */
  groups: DynamicPartitionGroup[]
  /**
   * Whether dynamic partitions have snapshots during the update. If this is
   * set to true, the update_engine daemon creates snapshots for all dynamic
   * partitions if possible. If this is unset, the update_engine daemon MUST
   * NOT create snapshots for dynamic partitions.
   */
  snapshotEnabled?: boolean | undefined
  /**
   * If this is set to false, update_engine should not use VABC regardless. If
   * this is set to true, update_engine may choose to use VABC if device
   * supports it, but not guaranteed.
   * VABC stands for Virtual AB Compression
   */
  vabcEnabled?: boolean | undefined
  /**
   * The compression algorithm used by VABC. Available ones are "gz", "brotli".
   * See system/core/fs_mgr/libsnapshot/cow_writer.cpp for available options,
   * as this parameter is ultimated forwarded to libsnapshot's CowWriter
   */
  vabcCompressionParam?: string | undefined
  /**
   * COW version used by VABC. The represents the major version in the COW
   * header
   */
  cowVersion?: number | undefined
  /** A collection of knobs to tune Virtual AB Compression */
  vabcFeatureSet?: VABCFeatureSet | undefined
  /**
   * Max bytes to be compressed at once during ota. Options: 4k, 8k, 16k, 32k,
   * 64k, 128k
   */
  compressionFactor?: number | undefined
  /**
   * Whether to disable UBLK for OTA. This will force dm-user as OTA backend
   * choice even if device was configured for UBLK based snapshots.
   */
  disableUblk?: boolean | undefined
}

/**
 * Definition has been duplicated from
 * $ANDROID_BUILD_TOP/build/tools/releasetools/ota_metadata.proto. Keep in sync.
 */
export interface ApexInfo {
  packageName?: string | undefined
  version?: number | undefined
  isCompressed?: boolean | undefined
  decompressedSize?: number | undefined
}

/**
 * Definition has been duplicated from
 * $ANDROID_BUILD_TOP/build/tools/releasetools/ota_metadata.proto. Keep in sync.
 */
export interface ApexMetadata {
  apexInfo: ApexInfo[]
}

export interface DeltaArchiveManifest {
  /** (At time of writing) usually 4096 */
  blockSize?: number | undefined
  /**
   * If signatures are present, the offset into the blobs, generally
   * tacked onto the end of the file, and the length. We use an offset
   * rather than a bool to allow for more flexibility in future file formats.
   * If either is absent, it means signatures aren't supported in this
   * file.
   */
  signaturesOffset?: number | undefined
  signaturesSize?: number | undefined
  /**
   * The minor version, also referred as "delta version", of the payload.
   * Minor version 0 is full payload, everything else is delta payload.
   */
  minorVersion?: number | undefined
  /**
   * Only present in major version >= 2. List of partitions that will be
   * updated, in the order they will be updated. This field replaces the
   * |install_operations|, |kernel_install_operations| and the
   * |{old,new}_{kernel,rootfs}_info| fields used in major version = 1. This
   * array can have more than two partitions if needed, and they are identified
   * by the partition name.
   */
  partitions: PartitionUpdate[]
  /**
   * The maximum timestamp of the OS allowed to apply this payload.
   * Can be used to prevent downgrading the OS.
   */
  maxTimestamp?: number | undefined
  /** Metadata related to all dynamic partitions. */
  dynamicPartitionMetadata?: DynamicPartitionMetadata | undefined
  /** If the payload only updates a subset of partitions on the device. */
  partialUpdate?: boolean | undefined
  /**
   * Information on compressed APEX to figure out how much space is required for
   * their decompression
   */
  apexInfo: ApexInfo[]
  /**
   * Security patch level of the device, usually in the format of
   * yyyy-mm-dd
   */
  securityPatchLevel?: string | undefined
}

function createBaseExtent(): Extent {
  return { startBlock: 0, numBlocks: 0 }
}

export const Extent: MessageFns<Extent> = {
  encode(message: Extent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.startBlock !== undefined && message.startBlock !== 0) {
      writer.uint32(8).uint64(message.startBlock)
    }
    if (message.numBlocks !== undefined && message.numBlocks !== 0) {
      writer.uint32(16).uint64(message.numBlocks)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Extent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseExtent()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.startBlock = longToNumber(reader.uint64())
          continue
        }
        case 2: {
          if (tag !== 16) {
            break
          }

          message.numBlocks = longToNumber(reader.uint64())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): Extent {
    return {
      startBlock: isSet(object.startBlock)
        ? globalThis.Number(object.startBlock)
        : isSet(object.start_block)
          ? globalThis.Number(object.start_block)
          : 0,
      numBlocks: isSet(object.numBlocks)
        ? globalThis.Number(object.numBlocks)
        : isSet(object.num_blocks)
          ? globalThis.Number(object.num_blocks)
          : 0
    }
  },

  toJSON(message: Extent): unknown {
    const obj: any = {}
    if (message.startBlock !== undefined && message.startBlock !== 0) {
      obj.startBlock = Math.round(message.startBlock)
    }
    if (message.numBlocks !== undefined && message.numBlocks !== 0) {
      obj.numBlocks = Math.round(message.numBlocks)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<Extent>, I>>(base?: I): Extent {
    return Extent.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<Extent>, I>>(object: I): Extent {
    const message = createBaseExtent()
    message.startBlock = object.startBlock ?? 0
    message.numBlocks = object.numBlocks ?? 0
    return message
  }
}

function createBaseSignatures(): Signatures {
  return { signatures: [] }
}

export const Signatures: MessageFns<Signatures> = {
  encode(message: Signatures, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.signatures) {
      Signatures_Signature.encode(v!, writer.uint32(10).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Signatures {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseSignatures()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.signatures.push(Signatures_Signature.decode(reader, reader.uint32()))
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): Signatures {
    return {
      signatures: globalThis.Array.isArray(object?.signatures)
        ? object.signatures.map((e: any) => Signatures_Signature.fromJSON(e))
        : []
    }
  },

  toJSON(message: Signatures): unknown {
    const obj: any = {}
    if (message.signatures?.length) {
      obj.signatures = message.signatures.map((e) => Signatures_Signature.toJSON(e))
    }
    return obj
  },

  create<I extends Exact<DeepPartial<Signatures>, I>>(base?: I): Signatures {
    return Signatures.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<Signatures>, I>>(object: I): Signatures {
    const message = createBaseSignatures()
    message.signatures = object.signatures?.map((e) => Signatures_Signature.fromPartial(e)) || []
    return message
  }
}

function createBaseSignatures_Signature(): Signatures_Signature {
  return { version: 0, data: new Uint8Array(0), unpaddedSignatureSize: 0 }
}

export const Signatures_Signature: MessageFns<Signatures_Signature> = {
  encode(message: Signatures_Signature, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version !== undefined && message.version !== 0) {
      writer.uint32(8).uint32(message.version)
    }
    if (message.data !== undefined && message.data.length !== 0) {
      writer.uint32(18).bytes(message.data)
    }
    if (message.unpaddedSignatureSize !== undefined && message.unpaddedSignatureSize !== 0) {
      writer.uint32(29).fixed32(message.unpaddedSignatureSize)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Signatures_Signature {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseSignatures_Signature()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.version = reader.uint32()
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.data = reader.bytes()
          continue
        }
        case 3: {
          if (tag !== 29) {
            break
          }

          message.unpaddedSignatureSize = reader.fixed32()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): Signatures_Signature {
    return {
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      data: isSet(object.data) ? bytesFromBase64(object.data) : new Uint8Array(0),
      unpaddedSignatureSize: isSet(object.unpaddedSignatureSize)
        ? globalThis.Number(object.unpaddedSignatureSize)
        : isSet(object.unpadded_signature_size)
          ? globalThis.Number(object.unpadded_signature_size)
          : 0
    }
  },

  toJSON(message: Signatures_Signature): unknown {
    const obj: any = {}
    if (message.version !== undefined && message.version !== 0) {
      obj.version = Math.round(message.version)
    }
    if (message.data !== undefined && message.data.length !== 0) {
      obj.data = base64FromBytes(message.data)
    }
    if (message.unpaddedSignatureSize !== undefined && message.unpaddedSignatureSize !== 0) {
      obj.unpaddedSignatureSize = Math.round(message.unpaddedSignatureSize)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<Signatures_Signature>, I>>(base?: I): Signatures_Signature {
    return Signatures_Signature.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<Signatures_Signature>, I>>(
    object: I
  ): Signatures_Signature {
    const message = createBaseSignatures_Signature()
    message.version = object.version ?? 0
    message.data = object.data ?? new Uint8Array(0)
    message.unpaddedSignatureSize = object.unpaddedSignatureSize ?? 0
    return message
  }
}

function createBasePartitionInfo(): PartitionInfo {
  return { size: 0, hash: new Uint8Array(0) }
}

export const PartitionInfo: MessageFns<PartitionInfo> = {
  encode(message: PartitionInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.size !== undefined && message.size !== 0) {
      writer.uint32(8).uint64(message.size)
    }
    if (message.hash !== undefined && message.hash.length !== 0) {
      writer.uint32(18).bytes(message.hash)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PartitionInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBasePartitionInfo()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.size = longToNumber(reader.uint64())
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.hash = reader.bytes()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): PartitionInfo {
    return {
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      hash: isSet(object.hash) ? bytesFromBase64(object.hash) : new Uint8Array(0)
    }
  },

  toJSON(message: PartitionInfo): unknown {
    const obj: any = {}
    if (message.size !== undefined && message.size !== 0) {
      obj.size = Math.round(message.size)
    }
    if (message.hash !== undefined && message.hash.length !== 0) {
      obj.hash = base64FromBytes(message.hash)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<PartitionInfo>, I>>(base?: I): PartitionInfo {
    return PartitionInfo.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<PartitionInfo>, I>>(object: I): PartitionInfo {
    const message = createBasePartitionInfo()
    message.size = object.size ?? 0
    message.hash = object.hash ?? new Uint8Array(0)
    return message
  }
}

function createBaseInstallOperation(): InstallOperation {
  return {
    type: 0,
    dataOffset: 0,
    dataLength: 0,
    srcExtents: [],
    srcLength: 0,
    dstExtents: [],
    dstLength: 0,
    dataSha256Hash: new Uint8Array(0),
    srcSha256Hash: new Uint8Array(0)
  }
}

export const InstallOperation: MessageFns<InstallOperation> = {
  encode(message: InstallOperation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type)
    }
    if (message.dataOffset !== undefined && message.dataOffset !== 0) {
      writer.uint32(16).uint64(message.dataOffset)
    }
    if (message.dataLength !== undefined && message.dataLength !== 0) {
      writer.uint32(24).uint64(message.dataLength)
    }
    for (const v of message.srcExtents) {
      Extent.encode(v!, writer.uint32(34).fork()).join()
    }
    if (message.srcLength !== undefined && message.srcLength !== 0) {
      writer.uint32(40).uint64(message.srcLength)
    }
    for (const v of message.dstExtents) {
      Extent.encode(v!, writer.uint32(50).fork()).join()
    }
    if (message.dstLength !== undefined && message.dstLength !== 0) {
      writer.uint32(56).uint64(message.dstLength)
    }
    if (message.dataSha256Hash !== undefined && message.dataSha256Hash.length !== 0) {
      writer.uint32(66).bytes(message.dataSha256Hash)
    }
    if (message.srcSha256Hash !== undefined && message.srcSha256Hash.length !== 0) {
      writer.uint32(74).bytes(message.srcSha256Hash)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InstallOperation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseInstallOperation()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.type = reader.int32() as any
          continue
        }
        case 2: {
          if (tag !== 16) {
            break
          }

          message.dataOffset = longToNumber(reader.uint64())
          continue
        }
        case 3: {
          if (tag !== 24) {
            break
          }

          message.dataLength = longToNumber(reader.uint64())
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.srcExtents.push(Extent.decode(reader, reader.uint32()))
          continue
        }
        case 5: {
          if (tag !== 40) {
            break
          }

          message.srcLength = longToNumber(reader.uint64())
          continue
        }
        case 6: {
          if (tag !== 50) {
            break
          }

          message.dstExtents.push(Extent.decode(reader, reader.uint32()))
          continue
        }
        case 7: {
          if (tag !== 56) {
            break
          }

          message.dstLength = longToNumber(reader.uint64())
          continue
        }
        case 8: {
          if (tag !== 66) {
            break
          }

          message.dataSha256Hash = reader.bytes()
          continue
        }
        case 9: {
          if (tag !== 74) {
            break
          }

          message.srcSha256Hash = reader.bytes()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): InstallOperation {
    return {
      type: isSet(object.type) ? installOperation_TypeFromJSON(object.type) : 0,
      dataOffset: isSet(object.dataOffset)
        ? globalThis.Number(object.dataOffset)
        : isSet(object.data_offset)
          ? globalThis.Number(object.data_offset)
          : 0,
      dataLength: isSet(object.dataLength)
        ? globalThis.Number(object.dataLength)
        : isSet(object.data_length)
          ? globalThis.Number(object.data_length)
          : 0,
      srcExtents: globalThis.Array.isArray(object?.srcExtents)
        ? object.srcExtents.map((e: any) => Extent.fromJSON(e))
        : globalThis.Array.isArray(object?.src_extents)
          ? object.src_extents.map((e: any) => Extent.fromJSON(e))
          : [],
      srcLength: isSet(object.srcLength)
        ? globalThis.Number(object.srcLength)
        : isSet(object.src_length)
          ? globalThis.Number(object.src_length)
          : 0,
      dstExtents: globalThis.Array.isArray(object?.dstExtents)
        ? object.dstExtents.map((e: any) => Extent.fromJSON(e))
        : globalThis.Array.isArray(object?.dst_extents)
          ? object.dst_extents.map((e: any) => Extent.fromJSON(e))
          : [],
      dstLength: isSet(object.dstLength)
        ? globalThis.Number(object.dstLength)
        : isSet(object.dst_length)
          ? globalThis.Number(object.dst_length)
          : 0,
      dataSha256Hash: isSet(object.dataSha256Hash)
        ? bytesFromBase64(object.dataSha256Hash)
        : isSet(object.data_sha256_hash)
          ? bytesFromBase64(object.data_sha256_hash)
          : new Uint8Array(0),
      srcSha256Hash: isSet(object.srcSha256Hash)
        ? bytesFromBase64(object.srcSha256Hash)
        : isSet(object.src_sha256_hash)
          ? bytesFromBase64(object.src_sha256_hash)
          : new Uint8Array(0)
    }
  },

  toJSON(message: InstallOperation): unknown {
    const obj: any = {}
    if (message.type !== 0) {
      obj.type = installOperation_TypeToJSON(message.type)
    }
    if (message.dataOffset !== undefined && message.dataOffset !== 0) {
      obj.dataOffset = Math.round(message.dataOffset)
    }
    if (message.dataLength !== undefined && message.dataLength !== 0) {
      obj.dataLength = Math.round(message.dataLength)
    }
    if (message.srcExtents?.length) {
      obj.srcExtents = message.srcExtents.map((e) => Extent.toJSON(e))
    }
    if (message.srcLength !== undefined && message.srcLength !== 0) {
      obj.srcLength = Math.round(message.srcLength)
    }
    if (message.dstExtents?.length) {
      obj.dstExtents = message.dstExtents.map((e) => Extent.toJSON(e))
    }
    if (message.dstLength !== undefined && message.dstLength !== 0) {
      obj.dstLength = Math.round(message.dstLength)
    }
    if (message.dataSha256Hash !== undefined && message.dataSha256Hash.length !== 0) {
      obj.dataSha256Hash = base64FromBytes(message.dataSha256Hash)
    }
    if (message.srcSha256Hash !== undefined && message.srcSha256Hash.length !== 0) {
      obj.srcSha256Hash = base64FromBytes(message.srcSha256Hash)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<InstallOperation>, I>>(base?: I): InstallOperation {
    return InstallOperation.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<InstallOperation>, I>>(object: I): InstallOperation {
    const message = createBaseInstallOperation()
    message.type = object.type ?? 0
    message.dataOffset = object.dataOffset ?? 0
    message.dataLength = object.dataLength ?? 0
    message.srcExtents = object.srcExtents?.map((e) => Extent.fromPartial(e)) || []
    message.srcLength = object.srcLength ?? 0
    message.dstExtents = object.dstExtents?.map((e) => Extent.fromPartial(e)) || []
    message.dstLength = object.dstLength ?? 0
    message.dataSha256Hash = object.dataSha256Hash ?? new Uint8Array(0)
    message.srcSha256Hash = object.srcSha256Hash ?? new Uint8Array(0)
    return message
  }
}

function createBaseCowMergeOperation(): CowMergeOperation {
  return { type: 0, srcExtent: undefined, dstExtent: undefined, srcOffset: 0 }
}

export const CowMergeOperation: MessageFns<CowMergeOperation> = {
  encode(message: CowMergeOperation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== undefined && message.type !== 0) {
      writer.uint32(8).int32(message.type)
    }
    if (message.srcExtent !== undefined) {
      Extent.encode(message.srcExtent, writer.uint32(18).fork()).join()
    }
    if (message.dstExtent !== undefined) {
      Extent.encode(message.dstExtent, writer.uint32(26).fork()).join()
    }
    if (message.srcOffset !== undefined && message.srcOffset !== 0) {
      writer.uint32(32).uint32(message.srcOffset)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CowMergeOperation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseCowMergeOperation()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.type = reader.int32() as any
          continue
        }
        case 2: {
          if (tag !== 18) {
            break
          }

          message.srcExtent = Extent.decode(reader, reader.uint32())
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.dstExtent = Extent.decode(reader, reader.uint32())
          continue
        }
        case 4: {
          if (tag !== 32) {
            break
          }

          message.srcOffset = reader.uint32()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): CowMergeOperation {
    return {
      type: isSet(object.type) ? cowMergeOperation_TypeFromJSON(object.type) : 0,
      srcExtent: isSet(object.srcExtent)
        ? Extent.fromJSON(object.srcExtent)
        : isSet(object.src_extent)
          ? Extent.fromJSON(object.src_extent)
          : undefined,
      dstExtent: isSet(object.dstExtent)
        ? Extent.fromJSON(object.dstExtent)
        : isSet(object.dst_extent)
          ? Extent.fromJSON(object.dst_extent)
          : undefined,
      srcOffset: isSet(object.srcOffset)
        ? globalThis.Number(object.srcOffset)
        : isSet(object.src_offset)
          ? globalThis.Number(object.src_offset)
          : 0
    }
  },

  toJSON(message: CowMergeOperation): unknown {
    const obj: any = {}
    if (message.type !== undefined && message.type !== 0) {
      obj.type = cowMergeOperation_TypeToJSON(message.type)
    }
    if (message.srcExtent !== undefined) {
      obj.srcExtent = Extent.toJSON(message.srcExtent)
    }
    if (message.dstExtent !== undefined) {
      obj.dstExtent = Extent.toJSON(message.dstExtent)
    }
    if (message.srcOffset !== undefined && message.srcOffset !== 0) {
      obj.srcOffset = Math.round(message.srcOffset)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<CowMergeOperation>, I>>(base?: I): CowMergeOperation {
    return CowMergeOperation.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<CowMergeOperation>, I>>(object: I): CowMergeOperation {
    const message = createBaseCowMergeOperation()
    message.type = object.type ?? 0
    message.srcExtent =
      object.srcExtent !== undefined && object.srcExtent !== null
        ? Extent.fromPartial(object.srcExtent)
        : undefined
    message.dstExtent =
      object.dstExtent !== undefined && object.dstExtent !== null
        ? Extent.fromPartial(object.dstExtent)
        : undefined
    message.srcOffset = object.srcOffset ?? 0
    return message
  }
}

function createBasePartitionUpdate(): PartitionUpdate {
  return {
    partitionName: '',
    runPostinstall: false,
    postinstallPath: '',
    filesystemType: '',
    newPartitionSignature: [],
    oldPartitionInfo: undefined,
    newPartitionInfo: undefined,
    operations: [],
    postinstallOptional: false,
    hashTreeDataExtent: undefined,
    hashTreeExtent: undefined,
    hashTreeAlgorithm: '',
    hashTreeSalt: new Uint8Array(0),
    fecDataExtent: undefined,
    fecExtent: undefined,
    fecRoots: 2,
    version: '',
    mergeOperations: [],
    estimateCowSize: 0,
    estimateOpCountMax: 0
  }
}

export const PartitionUpdate: MessageFns<PartitionUpdate> = {
  encode(message: PartitionUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.partitionName !== '') {
      writer.uint32(10).string(message.partitionName)
    }
    if (message.runPostinstall !== undefined && message.runPostinstall !== false) {
      writer.uint32(16).bool(message.runPostinstall)
    }
    if (message.postinstallPath !== undefined && message.postinstallPath !== '') {
      writer.uint32(26).string(message.postinstallPath)
    }
    if (message.filesystemType !== undefined && message.filesystemType !== '') {
      writer.uint32(34).string(message.filesystemType)
    }
    for (const v of message.newPartitionSignature) {
      Signatures_Signature.encode(v!, writer.uint32(42).fork()).join()
    }
    if (message.oldPartitionInfo !== undefined) {
      PartitionInfo.encode(message.oldPartitionInfo, writer.uint32(50).fork()).join()
    }
    if (message.newPartitionInfo !== undefined) {
      PartitionInfo.encode(message.newPartitionInfo, writer.uint32(58).fork()).join()
    }
    for (const v of message.operations) {
      InstallOperation.encode(v!, writer.uint32(66).fork()).join()
    }
    if (message.postinstallOptional !== undefined && message.postinstallOptional !== false) {
      writer.uint32(72).bool(message.postinstallOptional)
    }
    if (message.hashTreeDataExtent !== undefined) {
      Extent.encode(message.hashTreeDataExtent, writer.uint32(82).fork()).join()
    }
    if (message.hashTreeExtent !== undefined) {
      Extent.encode(message.hashTreeExtent, writer.uint32(90).fork()).join()
    }
    if (message.hashTreeAlgorithm !== undefined && message.hashTreeAlgorithm !== '') {
      writer.uint32(98).string(message.hashTreeAlgorithm)
    }
    if (message.hashTreeSalt !== undefined && message.hashTreeSalt.length !== 0) {
      writer.uint32(106).bytes(message.hashTreeSalt)
    }
    if (message.fecDataExtent !== undefined) {
      Extent.encode(message.fecDataExtent, writer.uint32(114).fork()).join()
    }
    if (message.fecExtent !== undefined) {
      Extent.encode(message.fecExtent, writer.uint32(122).fork()).join()
    }
    if (message.fecRoots !== undefined && message.fecRoots !== 2) {
      writer.uint32(128).uint32(message.fecRoots)
    }
    if (message.version !== undefined && message.version !== '') {
      writer.uint32(138).string(message.version)
    }
    for (const v of message.mergeOperations) {
      CowMergeOperation.encode(v!, writer.uint32(146).fork()).join()
    }
    if (message.estimateCowSize !== undefined && message.estimateCowSize !== 0) {
      writer.uint32(152).uint64(message.estimateCowSize)
    }
    if (message.estimateOpCountMax !== undefined && message.estimateOpCountMax !== 0) {
      writer.uint32(160).uint64(message.estimateOpCountMax)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PartitionUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBasePartitionUpdate()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.partitionName = reader.string()
          continue
        }
        case 2: {
          if (tag !== 16) {
            break
          }

          message.runPostinstall = reader.bool()
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.postinstallPath = reader.string()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.filesystemType = reader.string()
          continue
        }
        case 5: {
          if (tag !== 42) {
            break
          }

          message.newPartitionSignature.push(Signatures_Signature.decode(reader, reader.uint32()))
          continue
        }
        case 6: {
          if (tag !== 50) {
            break
          }

          message.oldPartitionInfo = PartitionInfo.decode(reader, reader.uint32())
          continue
        }
        case 7: {
          if (tag !== 58) {
            break
          }

          message.newPartitionInfo = PartitionInfo.decode(reader, reader.uint32())
          continue
        }
        case 8: {
          if (tag !== 66) {
            break
          }

          message.operations.push(InstallOperation.decode(reader, reader.uint32()))
          continue
        }
        case 9: {
          if (tag !== 72) {
            break
          }

          message.postinstallOptional = reader.bool()
          continue
        }
        case 10: {
          if (tag !== 82) {
            break
          }

          message.hashTreeDataExtent = Extent.decode(reader, reader.uint32())
          continue
        }
        case 11: {
          if (tag !== 90) {
            break
          }

          message.hashTreeExtent = Extent.decode(reader, reader.uint32())
          continue
        }
        case 12: {
          if (tag !== 98) {
            break
          }

          message.hashTreeAlgorithm = reader.string()
          continue
        }
        case 13: {
          if (tag !== 106) {
            break
          }

          message.hashTreeSalt = reader.bytes()
          continue
        }
        case 14: {
          if (tag !== 114) {
            break
          }

          message.fecDataExtent = Extent.decode(reader, reader.uint32())
          continue
        }
        case 15: {
          if (tag !== 122) {
            break
          }

          message.fecExtent = Extent.decode(reader, reader.uint32())
          continue
        }
        case 16: {
          if (tag !== 128) {
            break
          }

          message.fecRoots = reader.uint32()
          continue
        }
        case 17: {
          if (tag !== 138) {
            break
          }

          message.version = reader.string()
          continue
        }
        case 18: {
          if (tag !== 146) {
            break
          }

          message.mergeOperations.push(CowMergeOperation.decode(reader, reader.uint32()))
          continue
        }
        case 19: {
          if (tag !== 152) {
            break
          }

          message.estimateCowSize = longToNumber(reader.uint64())
          continue
        }
        case 20: {
          if (tag !== 160) {
            break
          }

          message.estimateOpCountMax = longToNumber(reader.uint64())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): PartitionUpdate {
    return {
      partitionName: isSet(object.partitionName)
        ? globalThis.String(object.partitionName)
        : isSet(object.partition_name)
          ? globalThis.String(object.partition_name)
          : '',
      runPostinstall: isSet(object.runPostinstall)
        ? globalThis.Boolean(object.runPostinstall)
        : isSet(object.run_postinstall)
          ? globalThis.Boolean(object.run_postinstall)
          : false,
      postinstallPath: isSet(object.postinstallPath)
        ? globalThis.String(object.postinstallPath)
        : isSet(object.postinstall_path)
          ? globalThis.String(object.postinstall_path)
          : '',
      filesystemType: isSet(object.filesystemType)
        ? globalThis.String(object.filesystemType)
        : isSet(object.filesystem_type)
          ? globalThis.String(object.filesystem_type)
          : '',
      newPartitionSignature: globalThis.Array.isArray(object?.newPartitionSignature)
        ? object.newPartitionSignature.map((e: any) => Signatures_Signature.fromJSON(e))
        : globalThis.Array.isArray(object?.new_partition_signature)
          ? object.new_partition_signature.map((e: any) => Signatures_Signature.fromJSON(e))
          : [],
      oldPartitionInfo: isSet(object.oldPartitionInfo)
        ? PartitionInfo.fromJSON(object.oldPartitionInfo)
        : isSet(object.old_partition_info)
          ? PartitionInfo.fromJSON(object.old_partition_info)
          : undefined,
      newPartitionInfo: isSet(object.newPartitionInfo)
        ? PartitionInfo.fromJSON(object.newPartitionInfo)
        : isSet(object.new_partition_info)
          ? PartitionInfo.fromJSON(object.new_partition_info)
          : undefined,
      operations: globalThis.Array.isArray(object?.operations)
        ? object.operations.map((e: any) => InstallOperation.fromJSON(e))
        : [],
      postinstallOptional: isSet(object.postinstallOptional)
        ? globalThis.Boolean(object.postinstallOptional)
        : isSet(object.postinstall_optional)
          ? globalThis.Boolean(object.postinstall_optional)
          : false,
      hashTreeDataExtent: isSet(object.hashTreeDataExtent)
        ? Extent.fromJSON(object.hashTreeDataExtent)
        : isSet(object.hash_tree_data_extent)
          ? Extent.fromJSON(object.hash_tree_data_extent)
          : undefined,
      hashTreeExtent: isSet(object.hashTreeExtent)
        ? Extent.fromJSON(object.hashTreeExtent)
        : isSet(object.hash_tree_extent)
          ? Extent.fromJSON(object.hash_tree_extent)
          : undefined,
      hashTreeAlgorithm: isSet(object.hashTreeAlgorithm)
        ? globalThis.String(object.hashTreeAlgorithm)
        : isSet(object.hash_tree_algorithm)
          ? globalThis.String(object.hash_tree_algorithm)
          : '',
      hashTreeSalt: isSet(object.hashTreeSalt)
        ? bytesFromBase64(object.hashTreeSalt)
        : isSet(object.hash_tree_salt)
          ? bytesFromBase64(object.hash_tree_salt)
          : new Uint8Array(0),
      fecDataExtent: isSet(object.fecDataExtent)
        ? Extent.fromJSON(object.fecDataExtent)
        : isSet(object.fec_data_extent)
          ? Extent.fromJSON(object.fec_data_extent)
          : undefined,
      fecExtent: isSet(object.fecExtent)
        ? Extent.fromJSON(object.fecExtent)
        : isSet(object.fec_extent)
          ? Extent.fromJSON(object.fec_extent)
          : undefined,
      fecRoots: isSet(object.fecRoots)
        ? globalThis.Number(object.fecRoots)
        : isSet(object.fec_roots)
          ? globalThis.Number(object.fec_roots)
          : 2,
      version: isSet(object.version) ? globalThis.String(object.version) : '',
      mergeOperations: globalThis.Array.isArray(object?.mergeOperations)
        ? object.mergeOperations.map((e: any) => CowMergeOperation.fromJSON(e))
        : globalThis.Array.isArray(object?.merge_operations)
          ? object.merge_operations.map((e: any) => CowMergeOperation.fromJSON(e))
          : [],
      estimateCowSize: isSet(object.estimateCowSize)
        ? globalThis.Number(object.estimateCowSize)
        : isSet(object.estimate_cow_size)
          ? globalThis.Number(object.estimate_cow_size)
          : 0,
      estimateOpCountMax: isSet(object.estimateOpCountMax)
        ? globalThis.Number(object.estimateOpCountMax)
        : isSet(object.estimate_op_count_max)
          ? globalThis.Number(object.estimate_op_count_max)
          : 0
    }
  },

  toJSON(message: PartitionUpdate): unknown {
    const obj: any = {}
    if (message.partitionName !== '') {
      obj.partitionName = message.partitionName
    }
    if (message.runPostinstall !== undefined && message.runPostinstall !== false) {
      obj.runPostinstall = message.runPostinstall
    }
    if (message.postinstallPath !== undefined && message.postinstallPath !== '') {
      obj.postinstallPath = message.postinstallPath
    }
    if (message.filesystemType !== undefined && message.filesystemType !== '') {
      obj.filesystemType = message.filesystemType
    }
    if (message.newPartitionSignature?.length) {
      obj.newPartitionSignature = message.newPartitionSignature.map((e) =>
        Signatures_Signature.toJSON(e)
      )
    }
    if (message.oldPartitionInfo !== undefined) {
      obj.oldPartitionInfo = PartitionInfo.toJSON(message.oldPartitionInfo)
    }
    if (message.newPartitionInfo !== undefined) {
      obj.newPartitionInfo = PartitionInfo.toJSON(message.newPartitionInfo)
    }
    if (message.operations?.length) {
      obj.operations = message.operations.map((e) => InstallOperation.toJSON(e))
    }
    if (message.postinstallOptional !== undefined && message.postinstallOptional !== false) {
      obj.postinstallOptional = message.postinstallOptional
    }
    if (message.hashTreeDataExtent !== undefined) {
      obj.hashTreeDataExtent = Extent.toJSON(message.hashTreeDataExtent)
    }
    if (message.hashTreeExtent !== undefined) {
      obj.hashTreeExtent = Extent.toJSON(message.hashTreeExtent)
    }
    if (message.hashTreeAlgorithm !== undefined && message.hashTreeAlgorithm !== '') {
      obj.hashTreeAlgorithm = message.hashTreeAlgorithm
    }
    if (message.hashTreeSalt !== undefined && message.hashTreeSalt.length !== 0) {
      obj.hashTreeSalt = base64FromBytes(message.hashTreeSalt)
    }
    if (message.fecDataExtent !== undefined) {
      obj.fecDataExtent = Extent.toJSON(message.fecDataExtent)
    }
    if (message.fecExtent !== undefined) {
      obj.fecExtent = Extent.toJSON(message.fecExtent)
    }
    if (message.fecRoots !== undefined && message.fecRoots !== 2) {
      obj.fecRoots = Math.round(message.fecRoots)
    }
    if (message.version !== undefined && message.version !== '') {
      obj.version = message.version
    }
    if (message.mergeOperations?.length) {
      obj.mergeOperations = message.mergeOperations.map((e) => CowMergeOperation.toJSON(e))
    }
    if (message.estimateCowSize !== undefined && message.estimateCowSize !== 0) {
      obj.estimateCowSize = Math.round(message.estimateCowSize)
    }
    if (message.estimateOpCountMax !== undefined && message.estimateOpCountMax !== 0) {
      obj.estimateOpCountMax = Math.round(message.estimateOpCountMax)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<PartitionUpdate>, I>>(base?: I): PartitionUpdate {
    return PartitionUpdate.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<PartitionUpdate>, I>>(object: I): PartitionUpdate {
    const message = createBasePartitionUpdate()
    message.partitionName = object.partitionName ?? ''
    message.runPostinstall = object.runPostinstall ?? false
    message.postinstallPath = object.postinstallPath ?? ''
    message.filesystemType = object.filesystemType ?? ''
    message.newPartitionSignature =
      object.newPartitionSignature?.map((e) => Signatures_Signature.fromPartial(e)) || []
    message.oldPartitionInfo =
      object.oldPartitionInfo !== undefined && object.oldPartitionInfo !== null
        ? PartitionInfo.fromPartial(object.oldPartitionInfo)
        : undefined
    message.newPartitionInfo =
      object.newPartitionInfo !== undefined && object.newPartitionInfo !== null
        ? PartitionInfo.fromPartial(object.newPartitionInfo)
        : undefined
    message.operations = object.operations?.map((e) => InstallOperation.fromPartial(e)) || []
    message.postinstallOptional = object.postinstallOptional ?? false
    message.hashTreeDataExtent =
      object.hashTreeDataExtent !== undefined && object.hashTreeDataExtent !== null
        ? Extent.fromPartial(object.hashTreeDataExtent)
        : undefined
    message.hashTreeExtent =
      object.hashTreeExtent !== undefined && object.hashTreeExtent !== null
        ? Extent.fromPartial(object.hashTreeExtent)
        : undefined
    message.hashTreeAlgorithm = object.hashTreeAlgorithm ?? ''
    message.hashTreeSalt = object.hashTreeSalt ?? new Uint8Array(0)
    message.fecDataExtent =
      object.fecDataExtent !== undefined && object.fecDataExtent !== null
        ? Extent.fromPartial(object.fecDataExtent)
        : undefined
    message.fecExtent =
      object.fecExtent !== undefined && object.fecExtent !== null
        ? Extent.fromPartial(object.fecExtent)
        : undefined
    message.fecRoots = object.fecRoots ?? 2
    message.version = object.version ?? ''
    message.mergeOperations =
      object.mergeOperations?.map((e) => CowMergeOperation.fromPartial(e)) || []
    message.estimateCowSize = object.estimateCowSize ?? 0
    message.estimateOpCountMax = object.estimateOpCountMax ?? 0
    return message
  }
}

function createBaseDynamicPartitionGroup(): DynamicPartitionGroup {
  return { name: '', size: 0, partitionNames: [] }
}

export const DynamicPartitionGroup: MessageFns<DynamicPartitionGroup> = {
  encode(message: DynamicPartitionGroup, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== '') {
      writer.uint32(10).string(message.name)
    }
    if (message.size !== undefined && message.size !== 0) {
      writer.uint32(16).uint64(message.size)
    }
    for (const v of message.partitionNames) {
      writer.uint32(26).string(v!)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DynamicPartitionGroup {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseDynamicPartitionGroup()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.name = reader.string()
          continue
        }
        case 2: {
          if (tag !== 16) {
            break
          }

          message.size = longToNumber(reader.uint64())
          continue
        }
        case 3: {
          if (tag !== 26) {
            break
          }

          message.partitionNames.push(reader.string())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): DynamicPartitionGroup {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : '',
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      partitionNames: globalThis.Array.isArray(object?.partitionNames)
        ? object.partitionNames.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.partition_names)
          ? object.partition_names.map((e: any) => globalThis.String(e))
          : []
    }
  },

  toJSON(message: DynamicPartitionGroup): unknown {
    const obj: any = {}
    if (message.name !== '') {
      obj.name = message.name
    }
    if (message.size !== undefined && message.size !== 0) {
      obj.size = Math.round(message.size)
    }
    if (message.partitionNames?.length) {
      obj.partitionNames = message.partitionNames
    }
    return obj
  },

  create<I extends Exact<DeepPartial<DynamicPartitionGroup>, I>>(base?: I): DynamicPartitionGroup {
    return DynamicPartitionGroup.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<DynamicPartitionGroup>, I>>(
    object: I
  ): DynamicPartitionGroup {
    const message = createBaseDynamicPartitionGroup()
    message.name = object.name ?? ''
    message.size = object.size ?? 0
    message.partitionNames = object.partitionNames?.map((e) => e) || []
    return message
  }
}

function createBaseVABCFeatureSet(): VABCFeatureSet {
  return { threaded: false, batchWrites: false }
}

export const VABCFeatureSet: MessageFns<VABCFeatureSet> = {
  encode(message: VABCFeatureSet, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.threaded !== undefined && message.threaded !== false) {
      writer.uint32(8).bool(message.threaded)
    }
    if (message.batchWrites !== undefined && message.batchWrites !== false) {
      writer.uint32(16).bool(message.batchWrites)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VABCFeatureSet {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseVABCFeatureSet()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break
          }

          message.threaded = reader.bool()
          continue
        }
        case 2: {
          if (tag !== 16) {
            break
          }

          message.batchWrites = reader.bool()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): VABCFeatureSet {
    return {
      threaded: isSet(object.threaded) ? globalThis.Boolean(object.threaded) : false,
      batchWrites: isSet(object.batchWrites)
        ? globalThis.Boolean(object.batchWrites)
        : isSet(object.batch_writes)
          ? globalThis.Boolean(object.batch_writes)
          : false
    }
  },

  toJSON(message: VABCFeatureSet): unknown {
    const obj: any = {}
    if (message.threaded !== undefined && message.threaded !== false) {
      obj.threaded = message.threaded
    }
    if (message.batchWrites !== undefined && message.batchWrites !== false) {
      obj.batchWrites = message.batchWrites
    }
    return obj
  },

  create<I extends Exact<DeepPartial<VABCFeatureSet>, I>>(base?: I): VABCFeatureSet {
    return VABCFeatureSet.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<VABCFeatureSet>, I>>(object: I): VABCFeatureSet {
    const message = createBaseVABCFeatureSet()
    message.threaded = object.threaded ?? false
    message.batchWrites = object.batchWrites ?? false
    return message
  }
}

function createBaseDynamicPartitionMetadata(): DynamicPartitionMetadata {
  return {
    groups: [],
    snapshotEnabled: false,
    vabcEnabled: false,
    vabcCompressionParam: '',
    cowVersion: 0,
    vabcFeatureSet: undefined,
    compressionFactor: 0,
    disableUblk: false
  }
}

export const DynamicPartitionMetadata: MessageFns<DynamicPartitionMetadata> = {
  encode(
    message: DynamicPartitionMetadata,
    writer: BinaryWriter = new BinaryWriter()
  ): BinaryWriter {
    for (const v of message.groups) {
      DynamicPartitionGroup.encode(v!, writer.uint32(10).fork()).join()
    }
    if (message.snapshotEnabled !== undefined && message.snapshotEnabled !== false) {
      writer.uint32(16).bool(message.snapshotEnabled)
    }
    if (message.vabcEnabled !== undefined && message.vabcEnabled !== false) {
      writer.uint32(24).bool(message.vabcEnabled)
    }
    if (message.vabcCompressionParam !== undefined && message.vabcCompressionParam !== '') {
      writer.uint32(34).string(message.vabcCompressionParam)
    }
    if (message.cowVersion !== undefined && message.cowVersion !== 0) {
      writer.uint32(40).uint32(message.cowVersion)
    }
    if (message.vabcFeatureSet !== undefined) {
      VABCFeatureSet.encode(message.vabcFeatureSet, writer.uint32(50).fork()).join()
    }
    if (message.compressionFactor !== undefined && message.compressionFactor !== 0) {
      writer.uint32(56).uint64(message.compressionFactor)
    }
    if (message.disableUblk !== undefined && message.disableUblk !== false) {
      writer.uint32(64).bool(message.disableUblk)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DynamicPartitionMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseDynamicPartitionMetadata()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.groups.push(DynamicPartitionGroup.decode(reader, reader.uint32()))
          continue
        }
        case 2: {
          if (tag !== 16) {
            break
          }

          message.snapshotEnabled = reader.bool()
          continue
        }
        case 3: {
          if (tag !== 24) {
            break
          }

          message.vabcEnabled = reader.bool()
          continue
        }
        case 4: {
          if (tag !== 34) {
            break
          }

          message.vabcCompressionParam = reader.string()
          continue
        }
        case 5: {
          if (tag !== 40) {
            break
          }

          message.cowVersion = reader.uint32()
          continue
        }
        case 6: {
          if (tag !== 50) {
            break
          }

          message.vabcFeatureSet = VABCFeatureSet.decode(reader, reader.uint32())
          continue
        }
        case 7: {
          if (tag !== 56) {
            break
          }

          message.compressionFactor = longToNumber(reader.uint64())
          continue
        }
        case 8: {
          if (tag !== 64) {
            break
          }

          message.disableUblk = reader.bool()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): DynamicPartitionMetadata {
    return {
      groups: globalThis.Array.isArray(object?.groups)
        ? object.groups.map((e: any) => DynamicPartitionGroup.fromJSON(e))
        : [],
      snapshotEnabled: isSet(object.snapshotEnabled)
        ? globalThis.Boolean(object.snapshotEnabled)
        : isSet(object.snapshot_enabled)
          ? globalThis.Boolean(object.snapshot_enabled)
          : false,
      vabcEnabled: isSet(object.vabcEnabled)
        ? globalThis.Boolean(object.vabcEnabled)
        : isSet(object.vabc_enabled)
          ? globalThis.Boolean(object.vabc_enabled)
          : false,
      vabcCompressionParam: isSet(object.vabcCompressionParam)
        ? globalThis.String(object.vabcCompressionParam)
        : isSet(object.vabc_compression_param)
          ? globalThis.String(object.vabc_compression_param)
          : '',
      cowVersion: isSet(object.cowVersion)
        ? globalThis.Number(object.cowVersion)
        : isSet(object.cow_version)
          ? globalThis.Number(object.cow_version)
          : 0,
      vabcFeatureSet: isSet(object.vabcFeatureSet)
        ? VABCFeatureSet.fromJSON(object.vabcFeatureSet)
        : isSet(object.vabc_feature_set)
          ? VABCFeatureSet.fromJSON(object.vabc_feature_set)
          : undefined,
      compressionFactor: isSet(object.compressionFactor)
        ? globalThis.Number(object.compressionFactor)
        : isSet(object.compression_factor)
          ? globalThis.Number(object.compression_factor)
          : 0,
      disableUblk: isSet(object.disableUblk)
        ? globalThis.Boolean(object.disableUblk)
        : isSet(object.disable_ublk)
          ? globalThis.Boolean(object.disable_ublk)
          : false
    }
  },

  toJSON(message: DynamicPartitionMetadata): unknown {
    const obj: any = {}
    if (message.groups?.length) {
      obj.groups = message.groups.map((e) => DynamicPartitionGroup.toJSON(e))
    }
    if (message.snapshotEnabled !== undefined && message.snapshotEnabled !== false) {
      obj.snapshotEnabled = message.snapshotEnabled
    }
    if (message.vabcEnabled !== undefined && message.vabcEnabled !== false) {
      obj.vabcEnabled = message.vabcEnabled
    }
    if (message.vabcCompressionParam !== undefined && message.vabcCompressionParam !== '') {
      obj.vabcCompressionParam = message.vabcCompressionParam
    }
    if (message.cowVersion !== undefined && message.cowVersion !== 0) {
      obj.cowVersion = Math.round(message.cowVersion)
    }
    if (message.vabcFeatureSet !== undefined) {
      obj.vabcFeatureSet = VABCFeatureSet.toJSON(message.vabcFeatureSet)
    }
    if (message.compressionFactor !== undefined && message.compressionFactor !== 0) {
      obj.compressionFactor = Math.round(message.compressionFactor)
    }
    if (message.disableUblk !== undefined && message.disableUblk !== false) {
      obj.disableUblk = message.disableUblk
    }
    return obj
  },

  create<I extends Exact<DeepPartial<DynamicPartitionMetadata>, I>>(
    base?: I
  ): DynamicPartitionMetadata {
    return DynamicPartitionMetadata.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<DynamicPartitionMetadata>, I>>(
    object: I
  ): DynamicPartitionMetadata {
    const message = createBaseDynamicPartitionMetadata()
    message.groups = object.groups?.map((e) => DynamicPartitionGroup.fromPartial(e)) || []
    message.snapshotEnabled = object.snapshotEnabled ?? false
    message.vabcEnabled = object.vabcEnabled ?? false
    message.vabcCompressionParam = object.vabcCompressionParam ?? ''
    message.cowVersion = object.cowVersion ?? 0
    message.vabcFeatureSet =
      object.vabcFeatureSet !== undefined && object.vabcFeatureSet !== null
        ? VABCFeatureSet.fromPartial(object.vabcFeatureSet)
        : undefined
    message.compressionFactor = object.compressionFactor ?? 0
    message.disableUblk = object.disableUblk ?? false
    return message
  }
}

function createBaseApexInfo(): ApexInfo {
  return { packageName: '', version: 0, isCompressed: false, decompressedSize: 0 }
}

export const ApexInfo: MessageFns<ApexInfo> = {
  encode(message: ApexInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.packageName !== undefined && message.packageName !== '') {
      writer.uint32(10).string(message.packageName)
    }
    if (message.version !== undefined && message.version !== 0) {
      writer.uint32(16).int64(message.version)
    }
    if (message.isCompressed !== undefined && message.isCompressed !== false) {
      writer.uint32(24).bool(message.isCompressed)
    }
    if (message.decompressedSize !== undefined && message.decompressedSize !== 0) {
      writer.uint32(32).int64(message.decompressedSize)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApexInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseApexInfo()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.packageName = reader.string()
          continue
        }
        case 2: {
          if (tag !== 16) {
            break
          }

          message.version = longToNumber(reader.int64())
          continue
        }
        case 3: {
          if (tag !== 24) {
            break
          }

          message.isCompressed = reader.bool()
          continue
        }
        case 4: {
          if (tag !== 32) {
            break
          }

          message.decompressedSize = longToNumber(reader.int64())
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): ApexInfo {
    return {
      packageName: isSet(object.packageName)
        ? globalThis.String(object.packageName)
        : isSet(object.package_name)
          ? globalThis.String(object.package_name)
          : '',
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      isCompressed: isSet(object.isCompressed)
        ? globalThis.Boolean(object.isCompressed)
        : isSet(object.is_compressed)
          ? globalThis.Boolean(object.is_compressed)
          : false,
      decompressedSize: isSet(object.decompressedSize)
        ? globalThis.Number(object.decompressedSize)
        : isSet(object.decompressed_size)
          ? globalThis.Number(object.decompressed_size)
          : 0
    }
  },

  toJSON(message: ApexInfo): unknown {
    const obj: any = {}
    if (message.packageName !== undefined && message.packageName !== '') {
      obj.packageName = message.packageName
    }
    if (message.version !== undefined && message.version !== 0) {
      obj.version = Math.round(message.version)
    }
    if (message.isCompressed !== undefined && message.isCompressed !== false) {
      obj.isCompressed = message.isCompressed
    }
    if (message.decompressedSize !== undefined && message.decompressedSize !== 0) {
      obj.decompressedSize = Math.round(message.decompressedSize)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<ApexInfo>, I>>(base?: I): ApexInfo {
    return ApexInfo.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<ApexInfo>, I>>(object: I): ApexInfo {
    const message = createBaseApexInfo()
    message.packageName = object.packageName ?? ''
    message.version = object.version ?? 0
    message.isCompressed = object.isCompressed ?? false
    message.decompressedSize = object.decompressedSize ?? 0
    return message
  }
}

function createBaseApexMetadata(): ApexMetadata {
  return { apexInfo: [] }
}

export const ApexMetadata: MessageFns<ApexMetadata> = {
  encode(message: ApexMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.apexInfo) {
      ApexInfo.encode(v!, writer.uint32(10).fork()).join()
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApexMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseApexMetadata()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break
          }

          message.apexInfo.push(ApexInfo.decode(reader, reader.uint32()))
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): ApexMetadata {
    return {
      apexInfo: globalThis.Array.isArray(object?.apexInfo)
        ? object.apexInfo.map((e: any) => ApexInfo.fromJSON(e))
        : globalThis.Array.isArray(object?.apex_info)
          ? object.apex_info.map((e: any) => ApexInfo.fromJSON(e))
          : []
    }
  },

  toJSON(message: ApexMetadata): unknown {
    const obj: any = {}
    if (message.apexInfo?.length) {
      obj.apexInfo = message.apexInfo.map((e) => ApexInfo.toJSON(e))
    }
    return obj
  },

  create<I extends Exact<DeepPartial<ApexMetadata>, I>>(base?: I): ApexMetadata {
    return ApexMetadata.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<ApexMetadata>, I>>(object: I): ApexMetadata {
    const message = createBaseApexMetadata()
    message.apexInfo = object.apexInfo?.map((e) => ApexInfo.fromPartial(e)) || []
    return message
  }
}

function createBaseDeltaArchiveManifest(): DeltaArchiveManifest {
  return {
    blockSize: 4096,
    signaturesOffset: 0,
    signaturesSize: 0,
    minorVersion: 0,
    partitions: [],
    maxTimestamp: 0,
    dynamicPartitionMetadata: undefined,
    partialUpdate: false,
    apexInfo: [],
    securityPatchLevel: ''
  }
}

export const DeltaArchiveManifest: MessageFns<DeltaArchiveManifest> = {
  encode(message: DeltaArchiveManifest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.blockSize !== undefined && message.blockSize !== 4096) {
      writer.uint32(24).uint32(message.blockSize)
    }
    if (message.signaturesOffset !== undefined && message.signaturesOffset !== 0) {
      writer.uint32(32).uint64(message.signaturesOffset)
    }
    if (message.signaturesSize !== undefined && message.signaturesSize !== 0) {
      writer.uint32(40).uint64(message.signaturesSize)
    }
    if (message.minorVersion !== undefined && message.minorVersion !== 0) {
      writer.uint32(96).uint32(message.minorVersion)
    }
    for (const v of message.partitions) {
      PartitionUpdate.encode(v!, writer.uint32(106).fork()).join()
    }
    if (message.maxTimestamp !== undefined && message.maxTimestamp !== 0) {
      writer.uint32(112).int64(message.maxTimestamp)
    }
    if (message.dynamicPartitionMetadata !== undefined) {
      DynamicPartitionMetadata.encode(
        message.dynamicPartitionMetadata,
        writer.uint32(122).fork()
      ).join()
    }
    if (message.partialUpdate !== undefined && message.partialUpdate !== false) {
      writer.uint32(128).bool(message.partialUpdate)
    }
    for (const v of message.apexInfo) {
      ApexInfo.encode(v!, writer.uint32(138).fork()).join()
    }
    if (message.securityPatchLevel !== undefined && message.securityPatchLevel !== '') {
      writer.uint32(146).string(message.securityPatchLevel)
    }
    return writer
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeltaArchiveManifest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input)
    const end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseDeltaArchiveManifest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 3: {
          if (tag !== 24) {
            break
          }

          message.blockSize = reader.uint32()
          continue
        }
        case 4: {
          if (tag !== 32) {
            break
          }

          message.signaturesOffset = longToNumber(reader.uint64())
          continue
        }
        case 5: {
          if (tag !== 40) {
            break
          }

          message.signaturesSize = longToNumber(reader.uint64())
          continue
        }
        case 12: {
          if (tag !== 96) {
            break
          }

          message.minorVersion = reader.uint32()
          continue
        }
        case 13: {
          if (tag !== 106) {
            break
          }

          message.partitions.push(PartitionUpdate.decode(reader, reader.uint32()))
          continue
        }
        case 14: {
          if (tag !== 112) {
            break
          }

          message.maxTimestamp = longToNumber(reader.int64())
          continue
        }
        case 15: {
          if (tag !== 122) {
            break
          }

          message.dynamicPartitionMetadata = DynamicPartitionMetadata.decode(
            reader,
            reader.uint32()
          )
          continue
        }
        case 16: {
          if (tag !== 128) {
            break
          }

          message.partialUpdate = reader.bool()
          continue
        }
        case 17: {
          if (tag !== 138) {
            break
          }

          message.apexInfo.push(ApexInfo.decode(reader, reader.uint32()))
          continue
        }
        case 18: {
          if (tag !== 146) {
            break
          }

          message.securityPatchLevel = reader.string()
          continue
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skip(tag & 7)
    }
    return message
  },

  fromJSON(object: any): DeltaArchiveManifest {
    return {
      blockSize: isSet(object.blockSize)
        ? globalThis.Number(object.blockSize)
        : isSet(object.block_size)
          ? globalThis.Number(object.block_size)
          : 4096,
      signaturesOffset: isSet(object.signaturesOffset)
        ? globalThis.Number(object.signaturesOffset)
        : isSet(object.signatures_offset)
          ? globalThis.Number(object.signatures_offset)
          : 0,
      signaturesSize: isSet(object.signaturesSize)
        ? globalThis.Number(object.signaturesSize)
        : isSet(object.signatures_size)
          ? globalThis.Number(object.signatures_size)
          : 0,
      minorVersion: isSet(object.minorVersion)
        ? globalThis.Number(object.minorVersion)
        : isSet(object.minor_version)
          ? globalThis.Number(object.minor_version)
          : 0,
      partitions: globalThis.Array.isArray(object?.partitions)
        ? object.partitions.map((e: any) => PartitionUpdate.fromJSON(e))
        : [],
      maxTimestamp: isSet(object.maxTimestamp)
        ? globalThis.Number(object.maxTimestamp)
        : isSet(object.max_timestamp)
          ? globalThis.Number(object.max_timestamp)
          : 0,
      dynamicPartitionMetadata: isSet(object.dynamicPartitionMetadata)
        ? DynamicPartitionMetadata.fromJSON(object.dynamicPartitionMetadata)
        : isSet(object.dynamic_partition_metadata)
          ? DynamicPartitionMetadata.fromJSON(object.dynamic_partition_metadata)
          : undefined,
      partialUpdate: isSet(object.partialUpdate)
        ? globalThis.Boolean(object.partialUpdate)
        : isSet(object.partial_update)
          ? globalThis.Boolean(object.partial_update)
          : false,
      apexInfo: globalThis.Array.isArray(object?.apexInfo)
        ? object.apexInfo.map((e: any) => ApexInfo.fromJSON(e))
        : globalThis.Array.isArray(object?.apex_info)
          ? object.apex_info.map((e: any) => ApexInfo.fromJSON(e))
          : [],
      securityPatchLevel: isSet(object.securityPatchLevel)
        ? globalThis.String(object.securityPatchLevel)
        : isSet(object.security_patch_level)
          ? globalThis.String(object.security_patch_level)
          : ''
    }
  },

  toJSON(message: DeltaArchiveManifest): unknown {
    const obj: any = {}
    if (message.blockSize !== undefined && message.blockSize !== 4096) {
      obj.blockSize = Math.round(message.blockSize)
    }
    if (message.signaturesOffset !== undefined && message.signaturesOffset !== 0) {
      obj.signaturesOffset = Math.round(message.signaturesOffset)
    }
    if (message.signaturesSize !== undefined && message.signaturesSize !== 0) {
      obj.signaturesSize = Math.round(message.signaturesSize)
    }
    if (message.minorVersion !== undefined && message.minorVersion !== 0) {
      obj.minorVersion = Math.round(message.minorVersion)
    }
    if (message.partitions?.length) {
      obj.partitions = message.partitions.map((e) => PartitionUpdate.toJSON(e))
    }
    if (message.maxTimestamp !== undefined && message.maxTimestamp !== 0) {
      obj.maxTimestamp = Math.round(message.maxTimestamp)
    }
    if (message.dynamicPartitionMetadata !== undefined) {
      obj.dynamicPartitionMetadata = DynamicPartitionMetadata.toJSON(
        message.dynamicPartitionMetadata
      )
    }
    if (message.partialUpdate !== undefined && message.partialUpdate !== false) {
      obj.partialUpdate = message.partialUpdate
    }
    if (message.apexInfo?.length) {
      obj.apexInfo = message.apexInfo.map((e) => ApexInfo.toJSON(e))
    }
    if (message.securityPatchLevel !== undefined && message.securityPatchLevel !== '') {
      obj.securityPatchLevel = message.securityPatchLevel
    }
    return obj
  },

  create<I extends Exact<DeepPartial<DeltaArchiveManifest>, I>>(base?: I): DeltaArchiveManifest {
    return DeltaArchiveManifest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<DeltaArchiveManifest>, I>>(
    object: I
  ): DeltaArchiveManifest {
    const message = createBaseDeltaArchiveManifest()
    message.blockSize = object.blockSize ?? 4096
    message.signaturesOffset = object.signaturesOffset ?? 0
    message.signaturesSize = object.signaturesSize ?? 0
    message.minorVersion = object.minorVersion ?? 0
    message.partitions = object.partitions?.map((e) => PartitionUpdate.fromPartial(e)) || []
    message.maxTimestamp = object.maxTimestamp ?? 0
    message.dynamicPartitionMetadata =
      object.dynamicPartitionMetadata !== undefined && object.dynamicPartitionMetadata !== null
        ? DynamicPartitionMetadata.fromPartial(object.dynamicPartitionMetadata)
        : undefined
    message.partialUpdate = object.partialUpdate ?? false
    message.apexInfo = object.apexInfo?.map((e) => ApexInfo.fromPartial(e)) || []
    message.securityPatchLevel = object.securityPatchLevel ?? ''
    return message
  }
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, 'base64'))
  } else {
    const bin = globalThis.atob(b64)
    const arr = new Uint8Array(bin.length)
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i)
    }
    return arr
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString('base64')
  } else {
    const bin: string[] = []
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte))
    })
    return globalThis.btoa(bin.join(''))
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never }

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString())
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error('Value is larger than Number.MAX_SAFE_INTEGER')
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error('Value is smaller than Number.MIN_SAFE_INTEGER')
  }
  return num
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter
  decode(input: BinaryReader | Uint8Array, length?: number): T
  fromJSON(object: any): T
  toJSON(message: T): unknown
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T
}
