name: check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Run [ci, lint, format]
        run: |
          pnpm install --frozen-lockfile
          pnpm run lint
          pnpm run format --check --no-write
