name: check

on: [push, pull_request]

jobs:
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build container
        run: docker build --file ./app01/Dockerfile .

  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Run [ci, lint, format]
        run: |
          pnpm install --frozen-lockfile
          pnpm run lint
          pnpm run format --check --no-write
